### ISSUE TITLE
Global-Leak in outdated dependency to `ee-types`.

### ISSUE THREAD

**Issue by rcky** [eventEmitter/async-method#2]
Async method has an outdated reference to `ee-types`. The referenced version 0.1.x of `ee-types` leaks a global variable `Class` due to a missing comma in the types.js and should therefore be updated.

We found this due to tests that rely on [facr 0.1.2](https://github.com/eventEmitter/facr)

**Comment by linaGirl** [comment]
this library is deprecated and should be removed from other projects. 

removed from:
- [x] facr

anyway, the library was updated to es6 levels (> node 8.x)
